openapi: 3.1.0
info:
  title: Integration Developer API
  description: API documentation for the Integration Developer application.
  version: 3.1.0
servers:
  - url: http://localhost:8180
paths:
  /genres:
    get:
      summary: Get all genres
      responses:
        200:
          description: Successfully retrieved list of genres
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genre'
  /artists:
    get:
      summary: Get all artists
      responses:
        200:
          description: Successfully retrieved list of artists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
  /albums:
    get:
      summary: Get albums by artist name or artist ID
      parameters:
        - name: artistName
          in: query
          description: Name of the artist to filter by
          required: false
          schema:
            type: string
        - name: artistId
          in: query
          description: ID of the artist to filter by
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Successfully retrieved albums based on query parameters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
    post:
      summary: Create a new album
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                AlbumName:
                  type: string
                  example: test
                DateReleased:
                  type: string
                  format: date
                  example: 2024-01-01
                ArtistId:
                  type: integer
                  example: 11
                GenreId:
                  type: integer
                  example: 7
      responses:
        201:
          description: Successfully created album
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
  /album/{albumId}:
    get:
      summary: Get album details by album ID
      parameters:
        - name: albumId
          in: path
          description: ID of the album to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successfully retrieved album details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
  /artists-by-genre:
    get:
      summary: Get artists by genre name
      parameters:
        - name: genreName
          in: query
          description: Name of the genre to filter by
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved artists based on query parameters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'

components:
  schemas:
    Genre:
      type: object
      properties:
        GenreId:
          type: integer
        GenreName:
          type: string
    Artist:
      type: object
      properties:
        ArtistId:
          type: integer
        ArtistName:
          type: string
    Album:
      type: object
      properties:
        AlbumId:
          type: integer
        AlbumName:
          type: string
        DateReleased:
          type: string
          format: date
        ArtistId:
          type: integer
        GenreId:
          type: integer
