/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelPet } from './entityModelPet';


export interface CollectionModelEntityModelPetEmbedded { 
    pets?: Array<EntityModelPet>;
}

