/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionModelEntityModelCategoryEmbedded } from './collectionModelEntityModelCategoryEmbedded';
import { Link } from './link';


export interface CollectionModelEntityModelCategory { 
    _embedded?: CollectionModelEntityModelCategoryEmbedded;
    _links?: { [key: string]: Link; };
}

