/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelOrder } from './entityModelOrder';


export interface CollectionModelEntityModelOrderEmbedded { 
    orders?: Array<EntityModelOrder>;
}

