/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionModelEntityModelPetEmbedded } from './collectionModelEntityModelPetEmbedded';
import { Link } from './link';


export interface CollectionModelEntityModelPet { 
    _embedded?: CollectionModelEntityModelPetEmbedded;
    _links?: { [key: string]: Link; };
}

