/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PetXTag } from './petXTag';
import { Link } from './link';
import { PetXCategory } from './petXCategory';


export interface EntityModelPet { 
    name?: string;
    photoUrls?: Array<string>;
    tags?: Array<PetXTag>;
    petStatus?: EntityModelPet.PetStatusEnum;
    petCategories?: Array<PetXCategory>;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelPet {
    export type PetStatusEnum = 'AVAILABLE' | 'PENDING' | 'SOLD';
    export const PetStatusEnum = {
        Available: 'AVAILABLE' as PetStatusEnum,
        Pending: 'PENDING' as PetStatusEnum,
        Sold: 'SOLD' as PetStatusEnum
    };
}


