/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelOrder { 
    petId?: number;
    quantity?: number;
    shipDate?: string;
    orderStatus?: EntityModelOrder.OrderStatusEnum;
    complete?: boolean;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelOrder {
    export type OrderStatusEnum = 'PLACED' | 'APPROVED' | 'DELIVERED';
    export const OrderStatusEnum = {
        Placed: 'PLACED' as OrderStatusEnum,
        Approved: 'APPROVED' as OrderStatusEnum,
        Delivered: 'DELIVERED' as OrderStatusEnum
    };
}


