/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PetXTag } from './petXTag';
import { PetXCategory } from './petXCategory';


export interface PetRequestBody { 
    readonly id?: number;
    name?: string;
    photoUrls?: Array<string>;
    tags?: Array<PetXTag>;
    petStatus?: PetRequestBody.PetStatusEnum;
    petCategories?: Array<PetXCategory>;
}
export namespace PetRequestBody {
    export type PetStatusEnum = 'AVAILABLE' | 'PENDING' | 'SOLD';
    export const PetStatusEnum = {
        Available: 'AVAILABLE' as PetStatusEnum,
        Pending: 'PENDING' as PetStatusEnum,
        Sold: 'SOLD' as PetStatusEnum
    };
}


