/**
 * Order API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';
import { Pet } from './pet';


export interface PetXTag { 
    pet?: Pet;
    tag?: Tag;
}

