apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  key: API_KEY
                  name: api-key-env
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: global-env
            - name: FILTER_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: FILTER_INTERVAL
                  name: global-env
            - name: SPRING_DATASOURCE_PASSWORD
              value: meow
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/petstore
            - name: SPRING_DATASOURCE_USERNAME
              value: pet
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          image: backend
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8988
              protocol: TCP
            - containerPort: 8989
              protocol: TCP
      restartPolicy: Always
