apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8082
    - name: "8091"
      port: 8091
      targetPort: 8988
    - name: "8092"
      port: 8092
      targetPort: 8989
  selector:
    io.kompose.service: backend
