apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  key: API_KEY
                  name: api-key-env
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: global-env
            - name: FILTER_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: FILTER_INTERVAL
                  name: global-env
          image: frontend
          imagePullPolicy: Never
          name: frontend
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
