apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
            - --optimized
            - -Djboss.http.port=8080
          env:
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: change_me
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: meow
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/petstore
            - name: KC_DB_USERNAME
              value: pet
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: keycloak
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
          image: mykeycloak
          imagePullPolicy: IfNotPresent
          name: mykeycloak
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-data
      restartPolicy: Always
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
