apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: keycloak
