apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: music-app
  name: music-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: music-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: music-app
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: music
            - name: MYSQL_HOST
              value: 172.22.0.2
            - name: MYSQL_PASSWORD
              value: testpw
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: test
          image: music-app
          imagePullPolicy: Never
          name: music-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
