apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: music-app
  name: music-app
spec:
  ports:
    - name: "8180"
      port: 8180
      targetPort: 3000
  selector:
    io.kompose.service: music-app
