apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: music
            - name: MYSQL_PASSWORD
              value: testpw
            - name: MYSQL_ROOT_PASSWORD
              value: AsDas!27d
            - name: MYSQL_USER
              value: test
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/my.cnf
              name: mysql-cm0
              subPath: my.cnf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: my.cnf
                path: my.cnf
            name: mysql-cm0
          name: mysql-cm0
