apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 5432
  selector:
    io.kompose.service: postgres
