apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger-ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: swagger-ui
    spec:
      containers:
        - env:
            - name: ALLOW_CORS
              value: "false"
            - name: SWAGGER_JSON
              value: /app/openapi.yaml
          image: swaggerapi/swagger-ui
          imagePullPolicy: IfNotPresent
          name: swagger-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/openapi.yaml
              name: swagger-ui-cm0
              subPath: openapi.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: music-app.yaml
                path: openapi.yaml
            name: swagger-ui-cm0
          name: swagger-ui-cm0
